/* ================================ */
/*           layout.js             */
/* ================================ */

/* 导入 Google 字体 Geist 和 Geist_Mono */
import { Geist, Geist_Mono } from "next/font/google";

/* 导入全局 CSS 文件，包含 TailwindCSS 和主题变量 */
import "./globals.css";

/* 使用 Geist 字体，设置为变量方便在 CSS 中引用 */
const geistSans = Geist({
  variable: "--font-geist-sans", /* 定义无衬线字体变量 */
  subsets: ["latin"], /* 仅加载 Latin 字符集，减少字体加载时间 */
});

/* 使用 Geist_Mono 字体，同样设置为变量 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", /* 定义等宽字体变量 */
  subsets: ["latin"],
});

/* 定义页面元数据（SEO） */
export const metadata = {
  title: "Create Next App", /* 网页标题 */
  description: "Generated by create next app", /* 页面描述 */
};

/* 定义 RootLayout 组件，作为页面的根布局 */
export default function RootLayout({ children }) {
  return (
    <html lang="en"> {/* 设置页面的 HTML 语言为英语 */}
      <body
        /* 使用字体变量和 Tailwind 的 antialiased 类使文字更平滑 */
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* 渲染子组件内容 */}
      </body>
    </html>
  );
}